version: '2'
services:
  db_postgres:
    image: postgres:latest
    hostname: db_postgres
    container_name: db_postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
      - ./scripts/create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
  celery:
    build: './celery_tasks'
    depends_on:
      - redis

volumes:
  db-postgres:
    driver: local

#networks:
#  my-net:
#    external: true